app = "trillium-quotes"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"
  context = "python-quote-service"

[env]
  PORT = "8001"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
