app = "stock-project"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  BACKEND_INTERNAL_URL = "http://127.0.0.1:4000"
  STOCK_QUOTE_SERVICE_URL = "http://127.0.0.1:8001"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"
