export type SupportedSymbol =
  | "AAPL" | "MSFT" | "NVDA" | "AMZN" | "GOOGL" | "TSLA" | "META" | "BRK-B" | "UNH" | "V"
  | "JPM" | "LLY" | "AVGO" | "XOM" | "MA" | "JNJ" | "PG" | "COST" | "HD" | "ADBE"
  | "NFLX" | "AMD" | "DIS" | "CRM" | "INTC" | "PYPL" | "VOO" | "QQQ" | "SPY" | "BABA"
  | "PLTR" | "SOFI" | "U" | "SNOW" | "CRWD" | "NKE" | "SBUX" | "TGT" | "WMT" | "CVX"
  | "CAT" | "DE" | "GS" | "MS" | "SQ" | "COIN" | "SCHD" | "VTI" | "VT" | "GME" | "AMC" | "MSTR"
  | "RBLX" | "PEP" | "KO" | "BAC" | "T" | "VZ" | "PFE" | "MRK" | "ABBV" | "ORCL" | "CSCO"
  | "ACN" | "TXN" | "QCOM" | "MU" | "AMAT" | "UBER" | "ABNB" | "SHOP" | "SE" | "MELI" | "TSM";

export const SYMBOL_META: Record<SupportedSymbol, { name: string; basePrice: number }> = {
  AAPL: { name: "Apple Inc.", basePrice: 190 },
  MSFT: { name: "Microsoft Corp.", basePrice: 415 },
  NVDA: { name: "NVIDIA Corp.", basePrice: 900 },
  AMZN: { name: "Amazon.com Inc.", basePrice: 186 },
  GOOGL: { name: "Alphabet Inc.", basePrice: 171 },
  TSLA: { name: "Tesla Inc.", basePrice: 190 },
  META: { name: "Meta Platforms Inc.", basePrice: 495 },
  "BRK-B": { name: "Berkshire Hathaway Inc.", basePrice: 415 },
  UNH: { name: "UnitedHealth Group Inc.", basePrice: 480 },
  V: { name: "Visa Inc.", basePrice: 280 },
  JPM: { name: "JPMorgan Chase & Co.", basePrice: 195 },
  LLY: { name: "Eli Lilly and Co.", basePrice: 770 },
  AVGO: { name: "Broadcom Inc.", basePrice: 1300 },
  XOM: { name: "Exxon Mobil Corp.", basePrice: 120 },
  MA: { name: "Mastercard Inc.", basePrice: 470 },
  JNJ: { name: "Johnson & Johnson", basePrice: 160 },
  PG: { name: "Procter & Gamble Co.", basePrice: 160 },
  COST: { name: "Costco Wholesale Corp.", basePrice: 730 },
  HD: { name: "Home Depot Inc.", basePrice: 350 },
  ADBE: { name: "Adobe Inc.", basePrice: 500 },
  NFLX: { name: "Netflix Inc.", basePrice: 620 },
  AMD: { name: "Advanced Micro Devices Inc.", basePrice: 180 },
  DIS: { name: "Walt Disney Co.", basePrice: 110 },
  CRM: { name: "Salesforce Inc.", basePrice: 300 },
  INTC: { name: "Intel Corp.", basePrice: 40 },
  PYPL: { name: "PayPal Holdings Inc.", basePrice: 65 },
  VOO: { name: "Vanguard S&P 500 ETF", basePrice: 470 },
  QQQ: { name: "Invesco QQQ Trust", basePrice: 440 },
  SPY: { name: "SPDR S&P 500 ETF Trust", basePrice: 515 },
  BABA: { name: "Alibaba Group Holding Ltd.", basePrice: 136 },
  PLTR: { name: "Palantir Technologies Inc.", basePrice: 24 },
  SOFI: { name: "SoFi Technologies Inc.", basePrice: 8 },
  U: { name: "Unity Software Inc.", basePrice: 30 },
  SNOW: { name: "Snowflake Inc.", basePrice: 160 },
  CRWD: { name: "CrowdStrike Holdings Inc.", basePrice: 320 },
  NKE: { name: "Nike Inc.", basePrice: 95 },
  SBUX: { name: "Starbucks Corp.", basePrice: 88 },
  TGT: { name: "Target Corp.", basePrice: 170 },
  WMT: { name: "Walmart Inc.", basePrice: 60 },
  CVX: { name: "Chevron Corp.", basePrice: 155 },
  CAT: { name: "Caterpillar Inc.", basePrice: 350 },
  DE: { name: "Deere & Co.", basePrice: 390 },
  GS: { name: "Goldman Sachs Group Inc.", basePrice: 410 },
  MS: { name: "Morgan Stanley", basePrice: 90 },
  SQ: { name: "Block Inc.", basePrice: 75 },
  COIN: { name: "Coinbase Global Inc.", basePrice: 250 },
  SCHD: { name: "Schwab US Dividend Equity ETF", basePrice: 78 },
  VTI: { name: "Vanguard Total Stock Market ETF", basePrice: 260 },
  VT: { name: "Vanguard Total World Stock ETF", basePrice: 105 },
  GME: { name: "GameStop Corp.", basePrice: 15 },
  AMC: { name: "AMC Entertainment Holdings Inc.", basePrice: 4 },
  MSTR: { name: "MicroStrategy Inc.", basePrice: 1600 },
  RBLX: { name: "Roblox Corp.", basePrice: 35 },
  PEP: { name: "PepsiCo Inc.", basePrice: 175 },
  KO: { name: "Coca-Cola Co.", basePrice: 60 },
  BAC: { name: "Bank of America Corp.", basePrice: 38 },
  T: { name: "AT&T Inc.", basePrice: 17 },
  VZ: { name: "Verizon Communications Inc.", basePrice: 40 },
  PFE: { name: "Pfizer Inc.", basePrice: 28 },
  MRK: { name: "Merck & Co. Inc.", basePrice: 130 },
  ABBV: { name: "AbbVie Inc.", basePrice: 170 },
  ORCL: { name: "Oracle Corp.", basePrice: 120 },
  CSCO: { name: "Cisco Systems Inc.", basePrice: 50 },
  ACN: { name: "Accenture plc", basePrice: 330 },
  TXN: { name: "Texas Instruments Inc.", basePrice: 180 },
  QCOM: { name: "QUALCOMM Inc.", basePrice: 175 },
  MU: { name: "Micron Technology Inc.", basePrice: 120 },
  AMAT: { name: "Applied Materials Inc.", basePrice: 210 },
  UBER: { name: "Uber Technologies Inc.", basePrice: 70 },
  ABNB: { name: "Airbnb Inc.", basePrice: 160 },
  SHOP: { name: "Shopify Inc.", basePrice: 75 },
  SE: { name: "Sea Ltd.", basePrice: 60 },
  MELI: { name: "MercadoLibre Inc.", basePrice: 1500 },
  TSM: { name: "Taiwan Semiconductor Manufacturing Co.", basePrice: 140 }
};

export const SUPPORTED_SYMBOLS = Object.keys(SYMBOL_META) as SupportedSymbol[];
